### ISSUE TITLE
systray display no icons

### ISSUE THREAD

**Issue by killown** [Aylur/ags#169] opened 2023-11-07 16:13 UTC
(com.github.Aylur.ags:13183): Gjs-CRITICAL **: 13:12:33.147: Object .AgsButton (0x5611e6cc10a0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x5611e5c0e4d0 ==
#0   7ffd2ba222a0 I   resource:///com/github/Aylur/ags/widgets/widget.js:135 (12bbf41c5650 @ 179)
#1   5611e5cf5680 i   file:///home/neo/.config/ags/js/bar/buttons/SysTray.js:12 (28c6d2e24ec0 @ 25)
#2   5611e5cf55b8 i   resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266 (12bbf417c420 @ 139)

**Comment by killown** [comment] 2023-11-07 16:14
➜  ~ ags --version
1.5.1

**Comment by matt1432** [comment] 2023-11-07 16:41
This just seems like a problem in your config, not a bug in ags

**Comment by killown** [comment] 2023-11-07 22:35
> This just seems like a problem in your config, not a bug in ags

I am still trying to find out where is the issue, thanks for the tip

**Comment by matt1432** [comment] 2023-11-08 01:07
It could also be a bug with the Icon widget, which should be fixed soon

**Comment by Aylur** [comment] 2023-11-09 00:47
Show the code where you use SystemTray

**Comment by killown** [comment] 2023-11-10 23:04
fixed already after an update

**Closed** 2023-11-12 12:06 UTC
